### ISSUE TITLE
cloud-regionsrv-client conflicts with container-suseconnect

### ISSUE THREAD

**Issue by dcermak** [SUSE-Enceladus/cloud-regionsrv-client#86] opened 2022-08-25 07:04 UTC
cloud-regionsrv-client tries to create the file `/usr/lib/zypp/plugins/urlresolver/susecloud` without explicitly conflicting with `container-suseconnect` or obsoleting it:
https://github.com/SUSE-Enceladus/cloud-regionsrv-client/blob/b5399b6ac88dac17db1c7c9111d3f59ccca67a0b/cloud-regionsrv-client.spec#L170

This causes failures in the SLE BCI images if you try to install the public cloud patterns:
```
500edf9c12f6:/ # zypper -n in -t pattern Amazon_Web_Services_Instance_Init Amazon_Web_Services_Instance_Tools Amazon_Web_Services_Tools
# snip
File /usr/lib/zypp/plugins/urlresolver/susecloud
  from install of
     cloud-regionsrv-client-10.0.4-150000.6.73.1.noarch (SLE_BCI)
  conflicts with file from package
     container-suseconnect-2.3.0-4.17.1.x86_64 (@System)
```

Please rename this file or obsolete `container-suseconnect`.

**Comment by dcermak** [comment] 2022-08-25 11:41
Thanks!

**Comment by rjschwei** [comment] 2022-08-25 13:13
The file conflict was introduced by Miquel Sabaté with f13f1dfd in container-suseconnect https://github.com/SUSE/container-suseconnect/blob/master/cmd/container-suseconnect/main.go#L60

The urlresolver in cloud-regionsrv-client `/usr/lib/zypp/plugins/urlresolver/susecloud` was created and has existed since "Thu Jan 10 09:00:12 2019" as such `container-suseconnect` should contain the conflict. However we should try to understand what he intend of the change introduced in f13f1dfd in container-suseconnect was before simply plastering over it with a `Conflicts` directive.

The urlresolver provided with cloud-regionsrv-client is requires in order for every instance of every customer to access the SUSE update infrastructure. In addition cloud-regionsrv-client provides `/usr/sbin/containerbuild-regionsrv` which allows customers to build containers on SLES PAYG instances.

The intend of `container-suseconnect` is to allow containers themselves to be connected to SCC. Apparently the change introduced by Miquel with f13f1dfd was intended to allow containers that run on PAYG instance to connect to the update infrastructure.

As luck has it @mssola still works for SUSE and as such he can provide input on the intend of f13f1dfd. While this is a bit over 2 years ago hopefully Miquel can shed some light as to why the file conflict was created and why no `Conflicts:` directive was inserted into the `container-suseconnect` package when f13f1dfd was merged.

Then there is the other question we have to ask w.r.t. bsc#1200641, does it make sense to even install cloud-regionsrv-client in a container. This type of installation kind of implies that the user has interest to access the update infrastructure from a container but not having the host access the update infrastructure. For the use case where a BCI based container for example would run on a non SLE based host that would fail. In the case where the host is also SLE base the host should be registered in which case cloud-regionsrv-client has no business in the container. The container related components of cloud-regionsrv-client are strictly intended to enable container building on PAYG instances. Building a container inside a container appears to me as a usecase we might not want to support.

Until we understand teh connections between the work @mssola did and why the necessary `Conflict` was not added to `container-suseconnect` when the change was introduced I will hold #88

**Comment by mssola** [comment] 2022-08-30 09:46
From my side, it has been a couple of years since I moved out of the containers team, and this change is older than that, even before I passed the maintenance of `container-suseconnact` to @rhafer. All this is to say that I honestly don't recall the context for this change (and a good reminder on why people should write good git commit messages...), and so I cannot say whether or not I was aware of the urlresolver in `cloud-regionsrv-client` as you pointed out. Maybe back then they had different use cases and so it was right for both of them to co-exist?

I simply don't know, but the fact that I didn't add a `Conflict` back then I believe that testifies that back then we simply weren't aware of this possible conflict.

Thus, I'd say it's totally fine to add a `Conflict` into the package as you have it on #88, but check with someone from that team just in case. Sorry for not being more helpful!

**Closed** 2022-08-31 11:22 UTC
